### ISSUE TITLE
Prepare flexi-docs repository for contribution by others

### ISSUE THREAD

**Issue by ndjones** [nesi/research-developer-cloud#1]
Get the site ready for contributions from others, including a contribution.md e.g. https://github.com/athackst/mkdocs-simple-plugin/blob/main/CONTRIBUTING.md

**Comment by lbrick** [comment]
I suppose my assumption here would be, if its a small change/edit then its easier to open an issue and let us know where to update it. If they are wanting to contribute a large amount, example being a new section for user guides, I would assume its better to do that all locally rather then within the GitHub web interface.

The web interface also doesn't allow you to see the changes to the site as its not hosting it on a dev URL

**Comment by ndjones** [comment]
If we're looking to embrace a broad level of skill and contribution, then lower barriers are better. the web interface doesn't require any local setup, and provides ease of use for those unfamiliar with Git. so yea, we'd want to embrace contributions via the web interface, even if our processes to review and accept are run locally.
in terms of small changes, I personally find it easier to edit via the web, commit, and open a pull request. at least, that feels like the right thing to do, rather than take a similar amount of effort to document the request and require someone else to then interpret what I'm suggesting. it seems like it reduces ambiguity, and seems more efficient.

**Comment by lbrick** [comment]
Sounds good, ill try include something within the contribution doc to include editing small things via the GitHub web interface
